plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/kimtaeoh/.gemini/antigravity-ide/scratch/선문셔틀/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]